package io.fusionauth.app.guice;

import com.google.inject.Module;
import com.google.inject.multibindings.MapBinder;
import com.google.inject.util.Modules;
import com.inversoft.freemarker.FormatLocalDate;
import com.inversoft.freemarker.FormatZonedDateTime;
import com.inversoft.freemarker.Gravatar;
import com.inversoft.freemarker.IsJavaTime;
import com.inversoft.freemarker.IsZonedDateTimeBeforeNow;
import com.inversoft.maintenance.BaseNonMaintenanceModeModule;
import com.inversoft.maintenance.MaintenanceModeModules;
import com.inversoft.scheduler.LogAndRetainFailureHandler;
import com.inversoft.scheduler.ScheduleBinder;
import com.inversoft.util.LoggerTool;
import io.fusionauth.api.guice.APIModule;
import io.fusionauth.api.plugin.guice.PluginModule;
import io.fusionauth.api.scim.SCIMException;
import io.fusionauth.api.security.guice.JWTModule;
import io.fusionauth.api.service.FusionAuthAccessDeniedException;
import io.fusionauth.api.service.authentication.LoginAggregator;
import io.fusionauth.api.service.authentication.RegistrationCounterAggregator;
import io.fusionauth.api.service.email.FusionAuthExecutorsMetricsCollector;
import io.fusionauth.api.service.event.EventRetryQueueWorker;
import io.fusionauth.api.service.jwt.RefreshTokenReaper;
import io.fusionauth.api.service.messenger.MessageTemplateException;
import io.fusionauth.api.service.messenger.MessengerException;
import io.fusionauth.api.service.metrics.MetricsLogger;
import io.fusionauth.api.service.reactor.CommonPasswordLoader;
import io.fusionauth.api.service.reactor.ReactorUpdater;
import io.fusionauth.api.service.system.AuditLogReaper;
import io.fusionauth.api.service.system.DefaultSetupService;
import io.fusionauth.api.service.system.EventLogReaper;
import io.fusionauth.api.service.system.LocalizableErrorException;
import io.fusionauth.api.service.system.LoginRecordReaper;
import io.fusionauth.api.service.system.NodeManager;
import io.fusionauth.api.service.system.SetupService;
import io.fusionauth.api.service.system.WebhookEventLogReaper;
import io.fusionauth.api.service.usage.UsageStatsAgent;
import io.fusionauth.api.service.usage.UsageStatsCollector;
import io.fusionauth.api.service.usage.UsageStatsReaper;
import io.fusionauth.api.service.user.EmailPlusRunner;
import io.fusionauth.api.service.user.RequestFrequencyRecordReaper;
import io.fusionauth.api.service.user.UserExternalIdReaper;
import io.fusionauth.api.service.user.UserReaper;
import io.fusionauth.api.service.useraction.UserActionEndEventSender;
import io.fusionauth.api.service.useraction.UserAlreadyActionedException;
import io.fusionauth.app.FusionAuthMain;
import io.fusionauth.app.freemarker.CurrentLocation;
import io.fusionauth.app.freemarker.DisplayLocaleNames;
import io.fusionauth.app.freemarker.FlattenUserData;
import io.fusionauth.app.freemarker.FormFieldOptionsConverter;
import io.fusionauth.app.freemarker.HasOneRole;
import io.fusionauth.app.freemarker.Locales;
import io.fusionauth.app.freemarker.OptionalMessage;
import io.fusionauth.app.freemarker.PhoneNumberFormatter;
import io.fusionauth.app.freemarker.PhoneNumberParser;
import io.fusionauth.app.freemarker.StaticsModel;
import io.fusionauth.app.freemarker.Stringify;
import io.fusionauth.app.maintenance.FusionAuthMaintenanceModeModules;
import io.fusionauth.app.primeframework.FusionHTTPContextAuthSetup;
import io.fusionauth.app.primeframework.error.ExceptionExceptionHandler;
import io.fusionauth.app.primeframework.error.FusionAuthAccessDeniedExceptionHandler;
import io.fusionauth.app.primeframework.error.FusionAuthInvalidRefererExceptionHandler;
import io.fusionauth.app.primeframework.error.FusionAuthSCIMExceptionHandler;
import io.fusionauth.app.primeframework.error.LocalizableErrorExceptionExceptionHandler;
import io.fusionauth.app.primeframework.error.MessageTemplateExceptionHandler;
import io.fusionauth.app.primeframework.error.MessengerExceptionHandler;
import io.fusionauth.app.primeframework.error.UserAlreadyActionedExceptionExceptionHandler;
import io.fusionauth.app.primeframework.exceptions.InvalidRefererException;
import io.fusionauth.app.service.CleanUp;
import io.fusionauth.app.service.identityProvider.AppleIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.EpicGamesIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.FacebookIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.GoogleIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.IdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.LinkedInIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.NintendoIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.OpenIDConnectIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.SAMLv2IdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.SonyPSNIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.SteamIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.TwitchIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.TwitterIdentityProviderFrontendService;
import io.fusionauth.app.service.identityProvider.XboxIdentityProviderFrontendService;
import io.fusionauth.app.service.license.DefaultFrontEndLicensedFeaturesService;
import io.fusionauth.app.service.license.FrontEndLicensedFeaturesService;
import io.fusionauth.app.service.scim.DefaultSCIMFrontendService;
import io.fusionauth.app.service.scim.SCIMFrontendService;
import io.fusionauth.app.service.search.DefaultSearchFrontendService;
import io.fusionauth.app.service.search.SearchFrontendService;
import io.fusionauth.app.service.security.DefaultLoginIntentService;
import io.fusionauth.app.service.security.DefaultSSOService;
import io.fusionauth.app.service.security.DefaultTwoFactorFrontendService;
import io.fusionauth.app.service.security.LoginIntentService;
import io.fusionauth.app.service.security.SSOService;
import io.fusionauth.app.service.security.TwoFactorFrontendService;
import io.fusionauth.app.service.system.DefaultSystemLogFrontendService;
import io.fusionauth.app.service.system.SystemLogFrontendService;
import io.fusionauth.app.service.theme.DefaultSimpleThemeFrontendService;
import io.fusionauth.app.service.theme.SimpleThemeFrontendService;
import io.fusionauth.app.service.user.CustomFormFrontendService;
import io.fusionauth.app.service.user.DefaultCustomFormFrontendService;
import io.fusionauth.app.service.user.DefaultRegistrationFrontendService;
import io.fusionauth.app.service.user.DefaultUserPreferencesFrontendService;
import io.fusionauth.app.service.user.RegistrationFrontendService;
import io.fusionauth.app.service.user.UserPreferencesFrontendService;
import io.fusionauth.app.service.webauthn.DefaultWebAuthnFrontendService;
import io.fusionauth.app.service.webauthn.WebAuthnFrontendService;
import io.fusionauth.domain.provider.IdentityProviderType;
import java.time.LocalTime;
import java.util.Objects;
import java.util.concurrent.TimeUnit;
import org.primeframework.mvc.freemarker.guice.TemplateModelFactory;
import org.primeframework.mvc.guice.MVCModule;
import org.primeframework.mvc.workflow.TypedExceptionHandlerFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FusionAuthModule extends BaseNonMaintenanceModeModule {
  private static final Logger logger = LoggerFactory.getLogger(FusionAuthModule.class);
  
  private final boolean runSchedules;
  
  public FusionAuthModule(boolean paramBoolean) {
    this.runSchedules = paramBoolean;
  }
  
  protected void configure() {
    LoggerTool.logPrettyInfoMessage(logger, String.format("Starting FusionAuth version [%s]", new Object[] { Objects.requireNonNullElse(FusionAuthMain.class.getPackage().getImplementationVersion(), ":dev:") }));
    super.configure();
    bind(FusionHTTPContextAuthSetup.class).asEagerSingleton();
    install(Modules.override(new Module[] { (Module)new APIModule(this.runSchedules) }).with(new Module[] { (Module)new PluginModule() }));
    install(Modules.override(new Module[] { (Module)new MVCModule() }).with(new Module[] { (Module)new JWTModule(), (Module)new FusionAuthContentModule(), (Module)new FusionAuthPrimeFreeMarkerModule(), (Module)new FusionAuthMVCModule(), (Module)new FusionAuthMVCSecurityModule(), (Module)new FusionAuthWorkflowModule(), (Module)new TenantManagerModule(), (Module)new LegacyAdapterModule() }));
    bind(SetupService.class).to(DefaultSetupService.class);
    MapBinder mapBinder = MapBinder.newMapBinder(binder(), IdentityProviderType.class, IdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.Apple).to(AppleIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.EpicGames).to(EpicGamesIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.Facebook).to(FacebookIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.Google).to(GoogleIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.LinkedIn).to(LinkedInIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.Nintendo).to(NintendoIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.OpenIDConnect).to(OpenIDConnectIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.SAMLv2).to(SAMLv2IdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.SonyPSN).to(SonyPSNIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.Steam).to(SteamIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.Twitch).to(TwitchIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.Twitter).to(TwitterIdentityProviderFrontendService.class);
    mapBinder.addBinding(IdentityProviderType.Xbox).to(XboxIdentityProviderFrontendService.class);
    bind(CustomFormFrontendService.class).to(DefaultCustomFormFrontendService.class);
    bind(RegistrationFrontendService.class).to(DefaultRegistrationFrontendService.class);
    bind(TwoFactorFrontendService.class).to(DefaultTwoFactorFrontendService.class);
    bind(SSOService.class).to(DefaultSSOService.class);
    bind(SystemLogFrontendService.class).to(DefaultSystemLogFrontendService.class);
    bind(SearchFrontendService.class).to(DefaultSearchFrontendService.class);
    bind(FrontEndLicensedFeaturesService.class).to(DefaultFrontEndLicensedFeaturesService.class);
    bind(SCIMFrontendService.class).to(DefaultSCIMFrontendService.class);
    bind(WebAuthnFrontendService.class).to(DefaultWebAuthnFrontendService.class);
    bind(SimpleThemeFrontendService.class).to(DefaultSimpleThemeFrontendService.class);
    bind(UserPreferencesFrontendService.class).to(DefaultUserPreferencesFrontendService.class);
    bind(LoginIntentService.class).to(DefaultLoginIntentService.class);
    TemplateModelFactory.addSingletonModel(binder(), "function", "is_zoned_date_time_before_now", IsZonedDateTimeBeforeNow.class);
    TemplateModelFactory.addSingletonModel(binder(), "function", "is_java_time", IsJavaTime.class);
    TemplateModelFactory.addSingletonModel(binder(), "function", "format_zoned_date_time", FormatZonedDateTime.class);
    TemplateModelFactory.addSingletonModel(binder(), "function", "format_local_date", FormatLocalDate.class);
    TemplateModelFactory.addSingletonModel(binder(), "function", "gravatar", Gravatar.class);
    TemplateModelFactory.addSingletonModel(binder(), "fusionAuth", "flatten_data", FlattenUserData.class);
    TemplateModelFactory.addSingletonModel(binder(), "fusionAuth", "stringify", Stringify.class);
    TemplateModelFactory.addSingletonModel(binder(), "fusionAuth", "phone_parser", PhoneNumberParser.class);
    TemplateModelFactory.addSingletonModel(binder(), "fusionAuth", "phone_format", PhoneNumberFormatter.class);
    TemplateModelFactory.addSingletonModel(binder(), "fusionAuth", "statics", StaticsModel.class);
    TemplateModelFactory.addSingletonModel(binder(), "fusionAuth", "convert_themed_field_options", FormFieldOptionsConverter.class);
    TemplateModelFactory.addModel(binder(), "fusionAuth", "display_locale_names", DisplayLocaleNames.class);
    TemplateModelFactory.addModel(binder(), "fusionAuth", "has_one_role", HasOneRole.class);
    TemplateModelFactory.addModel(binder(), "fusionAuth", "optionalMessage", OptionalMessage.class);
    TemplateModelFactory.addModel(binder(), "fusionAuth", "locales", Locales.class);
    TemplateModelFactory.addModel(binder(), "fusionAuth", "currentLocation", CurrentLocation.class);
    ScheduleBinder scheduleBinder = ScheduleBinder.newScheduleBinder(binder());
    scheduleBinder.schedule(LoginAggregator.class, null, LogAndRetainFailureHandler.class, 173L, TimeUnit.SECONDS, false);
    scheduleBinder.schedule(RegistrationCounterAggregator.class, null, LogAndRetainFailureHandler.class, 174L, TimeUnit.SECONDS, false);
    scheduleBinder.schedule(UserActionEndEventSender.class, null, LogAndRetainFailureHandler.class, 67L, TimeUnit.SECONDS, false);
    scheduleBinder.schedule(UserExternalIdReaper.class, null, LogAndRetainFailureHandler.class, 811L, TimeUnit.SECONDS, false);
    scheduleBinder.schedule(RefreshTokenReaper.class, null, LogAndRetainFailureHandler.class, 2203L, TimeUnit.SECONDS, false);
    scheduleBinder.schedule(RequestFrequencyRecordReaper.class, null, LogAndRetainFailureHandler.class, 67L, TimeUnit.MINUTES, false);
    scheduleBinder.schedule(MetricsLogger.class, null, LogAndRetainFailureHandler.class, 13L, TimeUnit.MINUTES, true);
    scheduleBinder.schedule(EventRetryQueueWorker.class, null, LogAndRetainFailureHandler.class, 10L, TimeUnit.MINUTES, false);
    scheduleBinder.schedule(NodeManager.class, null, LogAndRetainFailureHandler.class, 37L, TimeUnit.SECONDS, false);
    scheduleBinder.schedule(AuditLogReaper.class, null, LogAndRetainFailureHandler.class, 13L, TimeUnit.MINUTES, false);
    scheduleBinder.schedule(EventLogReaper.class, null, LogAndRetainFailureHandler.class, 17L, TimeUnit.MINUTES, false);
    scheduleBinder.schedule(LoginRecordReaper.class, null, LogAndRetainFailureHandler.class, 7L, TimeUnit.MINUTES, false);
    scheduleBinder.schedule(UserReaper.class, null, LogAndRetainFailureHandler.class, 3L, TimeUnit.HOURS, false);
    scheduleBinder.schedule(CommonPasswordLoader.class, null, LogAndRetainFailureHandler.class, 13L, TimeUnit.HOURS, false);
    scheduleBinder.schedule(EmailPlusRunner.class, null, LogAndRetainFailureHandler.class, 59L, TimeUnit.MINUTES, false);
    scheduleBinder.schedule(ReactorUpdater.class, null, LogAndRetainFailureHandler.class, 179L, TimeUnit.MINUTES, true);
    scheduleBinder.schedule(FusionAuthExecutorsMetricsCollector.class, null, LogAndRetainFailureHandler.class, 57L, TimeUnit.SECONDS, true);
    scheduleBinder.scheduleDaily(UsageStatsCollector.class, null, LogAndRetainFailureHandler.class, LocalTime.of(0, 31));
    scheduleBinder.schedule(UsageStatsAgent.class, null, LogAndRetainFailureHandler.class, 479L, TimeUnit.MINUTES, false);
    scheduleBinder.schedule(UsageStatsReaper.class, null, LogAndRetainFailureHandler.class, 12L, TimeUnit.HOURS, false);
    scheduleBinder.schedule(WebhookEventLogReaper.class, null, LogAndRetainFailureHandler.class, 19L, TimeUnit.MINUTES, false);
    TypedExceptionHandlerFactory.addExceptionHandler(binder(), Exception.class, ExceptionExceptionHandler.class);
    TypedExceptionHandlerFactory.addExceptionHandler(binder(), FusionAuthAccessDeniedException.class, FusionAuthAccessDeniedExceptionHandler.class);
    TypedExceptionHandlerFactory.addExceptionHandler(binder(), InvalidRefererException.class, FusionAuthInvalidRefererExceptionHandler.class);
    TypedExceptionHandlerFactory.addExceptionHandler(binder(), MessengerException.class, MessengerExceptionHandler.class);
    TypedExceptionHandlerFactory.addExceptionHandler(binder(), MessageTemplateException.class, MessageTemplateExceptionHandler.class);
    TypedExceptionHandlerFactory.addExceptionHandler(binder(), SCIMException.class, FusionAuthSCIMExceptionHandler.class);
    TypedExceptionHandlerFactory.addExceptionHandler(binder(), LocalizableErrorException.class, LocalizableErrorExceptionExceptionHandler.class);
    TypedExceptionHandlerFactory.addExceptionHandler(binder(), UserAlreadyActionedException.class, UserAlreadyActionedExceptionExceptionHandler.class);
    bind(CleanUp.class).asEagerSingleton();
  }
  
  protected Class<? extends MaintenanceModeModules> maintenanceModeModulesType() {
    return (Class)FusionAuthMaintenanceModeModules.class;
  }
}
