package io.fusionauth.api.domain;

import io.fusionauth.domain.Entity;
import io.fusionauth.domain.EntityGrant;
import io.fusionauth.domain.EntityType;
import io.fusionauth.domain.EntityTypePermission;
import io.fusionauth.domain.search.EntityGrantSearchCriteria;
import io.fusionauth.domain.search.EntityTypeSearchCriteria;
import java.util.List;
import java.util.UUID;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Insert.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EntityMapper {
  public static final String SELECT_ENTITY = "SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entities AS e\n    INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n";
  
  public static final String SELECT_ENTITY_GRANT = "SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id,\n  eg.id                           AS eg_id,\n  eg.data                         AS eg_dataFromDatabase,\n  eg.insert_instant               AS eg_insertInstant,\n  eg.last_update_instant          AS eg_lastUpdateInstant,\n  eg.recipient_id                 AS eg_recipientEntityId,\n  etp2.name                       AS eg_permissions\nFROM entity_entity_grants         AS eg\n  INNER JOIN entities AS e ON e.id = eg.target_id\n  INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n  LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n  LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n  LEFT OUTER JOIN entity_entity_grant_permissions AS eegp ON eg.id = eegp.entity_entity_grants_id\n  LEFT OUTER JOIN entity_type_permissions AS etp2 ON eegp.entity_type_permissions_id = etp2.id\n";
  
  public static final String SELECT_TYPE = "SELECT\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entity_types AS et\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n";
  
  public static final String SELECT_USER_GRANT = "SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id,\n  eg.id                           AS eg_id,\n  eg.data                         AS eg_dataFromDatabase,\n  eg.insert_instant               AS eg_insertInstant,\n  eg.last_update_instant          AS eg_lastUpdateInstant,\n  eg.users_id                     AS eg_userId,\n  etp2.name                       AS eg_permissions\nFROM entity_user_grants AS eg\n  INNER JOIN entities AS e ON e.id = eg.entities_id\n  INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n  LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n  LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n  LEFT OUTER JOIN entity_user_grant_permissions AS eugp ON eg.id = eugp.entity_user_grants_id\n  LEFT OUTER JOIN entity_type_permissions AS etp2 ON eugp.entity_type_permissions_id = etp2.id\n";
  
  @Select({"SELECT COUNT(*) FROM entity_type_verification_keys WHERE entity_types_id = #{entityTypeId} AND type = #{type} AND is_default = true"})
  int countDefaultTypeVerificationKeys(@Param("entityTypeId") UUID paramUUID, @Param("type") String paramString);
  
  @Select({"<script>\nSELECT COUNT(eg.id) FROM\n<if test=\"userId != null\">\n  entity_user_grants AS eg\n    INNER JOIN entities AS e ON e.id = eg.entities_id\n</if>\n<if test=\"entityId != null\">\n  entity_entity_grants AS eg\n    INNER JOIN entities AS e ON e.id = eg.recipient_id\n</if>\n<where>\n<if test=\"userId != null\">\n  AND eg.users_id = #{userId}\n</if>\n<if test=\"entityId != null\">\n  AND eg.recipient_id = #{entityId}\n</if>\n<if test=\"name != null\">\n  AND LOWER(e.name) LIKE #{name}\n</if>\n</where>\n</script>\n"})
  int countGrants(EntityGrantSearchCriteria paramEntityGrantSearchCriteria);
  
  @Select({"<script>\nSELECT COUNT(id) FROM entity_types\n<if test=\"name != null\">\n  WHERE LOWER(name) LIKE #{name}\n</if>\n</script>\n"})
  int countTypes(EntityTypeSearchCriteria paramEntityTypeSearchCriteria);
  
  @Insert({"INSERT INTO entities (id, client_id, client_secret, data, entity_types_id, insert_instant, last_update_instant, name, parent_id, tenants_id)\nVALUES (#{id}, #{clientId}, #{clientSecret}, #{dataToDatabase}, #{type.id}, #{insertInstant}, #{lastUpdateInstant}, #{name}, #{parentId}, #{tenantId})\n"})
  void createEntity(Entity paramEntity);
  
  @Insert({"<script>\nINSERT INTO entity_entity_grant_permissions (entity_entity_grants_id, entity_type_permissions_id) VALUES\n<foreach collection=\"permissions\" item=\"permission\" separator=\",\">\n(#{grant.id}, #{permission.id})\n</foreach>\n</script>\n"})
  void createEntityGrantPermissions(@Param("grant") EntityGrant paramEntityGrant, @Param("permissions") List<EntityTypePermission> paramList);
  
  @Insert({"INSERT INTO entity_type_permissions (id, data, description, entity_types_id, insert_instant, is_default, last_update_instant, name)\nVALUES (#{id}, #{dataToDatabase}, #{description}, #{entityTypeId}, #{insertInstant}, #{isDefault}, #{lastUpdateInstant}, #{name})\n"})
  void createPermission(EntityTypePermission paramEntityTypePermission);
  
  @Insert({"INSERT INTO entity_types (id, access_token_signing_keys_id, data, name, insert_instant, last_update_instant) VALUES (#{id}, #{jwtConfiguration.accessTokenKeyId}, #{dataToDatabase}, #{name}, #{insertInstant}, #{lastUpdateInstant})"})
  void createType(EntityType paramEntityType);
  
  @Insert({"<script>\nINSERT INTO entity_type_verification_keys (entity_types_id, keys_id, type, is_default) VALUES\n<foreach collection=\"keyIds\" item=\"keyId\" index=\"i\" separator=\",\">\n  (#{entityTypeId}, #{keyId}, #{type},\n  <choose><when test=\"markDefault and i == 0\">true</when><otherwise>false</otherwise></choose>)\n</foreach>\n</script>\n"})
  void createTypeVerificationKeys(@Param("entityTypeId") UUID paramUUID, @Param("type") String paramString, @Param("keyIds") List<UUID> paramList, @Param("markDefault") boolean paramBoolean);
  
  @Insert({"<script>\nINSERT INTO entity_user_grant_permissions (entity_user_grants_id, entity_type_permissions_id) VALUES\n<foreach collection=\"permissions\" item=\"permission\" separator=\",\">\n(#{grant.id}, #{permission.id})\n</foreach>\n</script>\n"})
  void createUserGrantPermissions(@Param("grant") EntityGrant paramEntityGrant, @Param("permissions") List<EntityTypePermission> paramList);
  
  @Delete({"DELETE FROM entities WHERE id = #{id}"})
  void deleteEntity(@Param("id") UUID paramUUID);
  
  @Delete({"DELETE FROM entity_entity_grants WHERE id = #{id}"})
  void deleteEntityGrant(@Param("id") UUID paramUUID);
  
  @Delete({"DELETE FROM entity_entity_grant_permissions WHERE entity_entity_grants_id = #{id}"})
  void deleteEntityGrantPermissions(@Param("id") UUID paramUUID);
  
  @Delete({"DELETE FROM entity_entity_grant_permissions WHERE entity_type_permissions_id = #{permissionId}"})
  void deleteEntityPermissionGrants(@Param("permissionId") UUID paramUUID);
  
  @Delete({"DELETE FROM entity_type_permissions WHERE id = #{permissionId}"})
  void deletePermission(@Param("permissionId") UUID paramUUID);
  
  @Delete({"DELETE FROM entity_types WHERE id = #{id}"})
  void deleteType(@Param("id") UUID paramUUID);
  
  @Delete({"DELETE FROM entity_type_verification_keys WHERE entity_types_id = #{entityTypeId}"})
  void deleteTypeVerificationKeys(@Param("entityTypeId") UUID paramUUID);
  
  @Delete({"DELETE FROM entity_user_grants WHERE id = #{id}"})
  void deleteUserGrant(@Param("id") UUID paramUUID);
  
  @Delete({"DELETE FROM entity_user_grant_permissions WHERE entity_user_grants_id = #{id}"})
  void deleteUserGrantPermissions(@Param("id") UUID paramUUID);
  
  @Select({"SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entities AS e\n    INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n ORDER BY e.id, et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name"})
  @ResultMap({"Entity"})
  List<Entity> retrieveAll();
  
  @Select({"SELECT\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entity_types AS et\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n ORDER BY et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name"})
  @ResultMap({"EntityType"})
  List<EntityType> retrieveAllTypes();
  
  @Select({"SELECT count(*) FROM entities;\n"})
  long retrieveCountForReindex();
  
  @Select({"<script>SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entities AS e\n    INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\nWHERE e.id IN (\n  <foreach collection=\"ids\" item=\"id\" separator=\",\">#{id}</foreach>\n)\n<if test=\"tenantId != null\">\n  AND e.tenants_id = #{tenantId}\n</if>\nORDER BY e.id, et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name\n</script>"})
  @ResultMap({"Entity"})
  List<Entity> retrieveEntitiesByIds(@Param("tenantId") UUID paramUUID, @Param("ids") List<UUID> paramList);
  
  @Select({"<script>SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entities AS e\n    INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\nWHERE e.client_id = #{clientId}\n<if test=\"tenantId != null\">\n  AND e.tenants_id = #{tenantId}\n</if>\nORDER BY e.id, et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name\n</script>\n"})
  @ResultMap({"Entity"})
  Entity retrieveEntityByClientId(@Param("tenantId") UUID paramUUID, @Param("clientId") String paramString);
  
  @Select({"<script>SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entities AS e\n    INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\nWHERE e.id = #{id}\n<if test=\"tenantId != null\">\n  AND e.tenants_id = #{tenantId}\n</if>\nORDER BY e.id, et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name\n</script>\n"})
  @ResultMap({"Entity"})
  Entity retrieveEntityById(@Param("tenantId") UUID paramUUID1, @Param("id") UUID paramUUID2);
  
  @Select({"SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id,\n  eg.id                           AS eg_id,\n  eg.data                         AS eg_dataFromDatabase,\n  eg.insert_instant               AS eg_insertInstant,\n  eg.last_update_instant          AS eg_lastUpdateInstant,\n  eg.recipient_id                 AS eg_recipientEntityId,\n  etp2.name                       AS eg_permissions\nFROM entity_entity_grants         AS eg\n  INNER JOIN entities AS e ON e.id = eg.target_id\n  INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n  LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n  LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n  LEFT OUTER JOIN entity_entity_grant_permissions AS eegp ON eg.id = eegp.entity_entity_grants_id\n  LEFT OUTER JOIN entity_type_permissions AS etp2 ON eegp.entity_type_permissions_id = etp2.id\n WHERE eg.recipient_id = #{recipientId} AND eg.target_id = #{targetId} ORDER BY et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name, etp2.name"})
  @ResultMap({"EntityGrant"})
  EntityGrant retrieveEntityGrantForEntity(@Param("recipientId") UUID paramUUID1, @Param("targetId") UUID paramUUID2);
  
  @Select({"<script>SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id,\n  eg.id                           AS eg_id,\n  eg.data                         AS eg_dataFromDatabase,\n  eg.insert_instant               AS eg_insertInstant,\n  eg.last_update_instant          AS eg_lastUpdateInstant,\n  eg.recipient_id                 AS eg_recipientEntityId,\n  etp2.name                       AS eg_permissions\nFROM entity_entity_grants         AS eg\n  INNER JOIN entities AS e ON e.id = eg.target_id\n  INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n  LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n  LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n  LEFT OUTER JOIN entity_entity_grant_permissions AS eegp ON eg.id = eegp.entity_entity_grants_id\n  LEFT OUTER JOIN entity_type_permissions AS etp2 ON eegp.entity_type_permissions_id = etp2.id\nWHERE eg.id IN (\n  <foreach collection=\"ids\" item=\"id\" separator=\",\">#{id}</foreach>\n)\nORDER BY eg.id, et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name, etp2.name\n</script>\n"})
  @ResultMap({"EntityGrant"})
  List<EntityGrant> retrieveEntityGrantsByIds(@Param("ids") List<UUID> paramList);
  
  @Select({"SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id,\n  eg.id                           AS eg_id,\n  eg.data                         AS eg_dataFromDatabase,\n  eg.insert_instant               AS eg_insertInstant,\n  eg.last_update_instant          AS eg_lastUpdateInstant,\n  eg.recipient_id                 AS eg_recipientEntityId,\n  etp2.name                       AS eg_permissions\nFROM entity_entity_grants         AS eg\n  INNER JOIN entities AS e ON e.id = eg.target_id\n  INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n  LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n  LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n  LEFT OUTER JOIN entity_entity_grant_permissions AS eegp ON eg.id = eegp.entity_entity_grants_id\n  LEFT OUTER JOIN entity_type_permissions AS etp2 ON eegp.entity_type_permissions_id = etp2.id\n WHERE eg.target_id = #{entityId} ORDER BY eg.id, et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name, etp2.name"})
  @ResultMap({"EntityGrant"})
  List<EntityGrant> retrieveEntityGrantsForEntity(@Param("entityId") UUID paramUUID);
  
  @Select({"SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id,\n  eg.id                           AS eg_id,\n  eg.data                         AS eg_dataFromDatabase,\n  eg.insert_instant               AS eg_insertInstant,\n  eg.last_update_instant          AS eg_lastUpdateInstant,\n  eg.users_id                     AS eg_userId,\n  etp2.name                       AS eg_permissions\nFROM entity_user_grants AS eg\n  INNER JOIN entities AS e ON e.id = eg.entities_id\n  INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n  LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n  LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n  LEFT OUTER JOIN entity_user_grant_permissions AS eugp ON eg.id = eugp.entity_user_grants_id\n  LEFT OUTER JOIN entity_type_permissions AS etp2 ON eugp.entity_type_permissions_id = etp2.id\n WHERE eg.entities_id = #{entityId} AND eg.users_id = #{userId} ORDER BY et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name, etp2.name"})
  @ResultMap({"EntityGrant"})
  EntityGrant retrieveGrantForUser(@Param("entityId") UUID paramUUID1, @Param("userId") UUID paramUUID2);
  
  @Select({"<script>\nSELECT eg.id FROM\n<if test=\"userId != null\">\n  entity_user_grants AS eg\n    INNER JOIN entities AS e ON e.id = eg.entities_id\n</if>\n<if test=\"entityId != null\">\n  entity_entity_grants AS eg\n    INNER JOIN entities AS e ON e.id = eg.target_id\n</if>\n<where>\n<if test=\"userId != null\">\n  AND eg.users_id = #{userId}\n</if>\n<if test=\"entityId != null\">\n  AND eg.recipient_id = #{entityId}\n</if>\n<if test=\"name != null\">\n  AND LOWER(e.name) LIKE #{name}\n</if>\n</where>\n<if test=\"orderBy != null\">\n  ORDER BY ${orderBy}\n</if>\nLIMIT #{numberOfResults}\nOFFSET #{startRow}\n</script>\n"})
  List<UUID> retrieveGrantIdsByCriteria(EntityGrantSearchCriteria paramEntityGrantSearchCriteria);
  
  @Select({"SELECT etp.id              AS etp_id,\n       etp.data            AS etp_data,\n       etp.description     AS etp_description,\n       etp.entity_types_id AS etp_entity_types_id,\n       etp.insert_instant  AS etp_insert_instant,\n       etp.is_default      AS etp_is_default,\n       etp.last_update_instant AS etp_last_update_instant,\n       etp.name            AS etp_name\n  FROM entity_type_permissions AS etp\n WHERE etp.entity_types_id = #{entityTypeId}\n   AND etp.id = #{permissionId}\n"})
  @ResultMap({"EntityTypePermission"})
  EntityTypePermission retrievePermissionById(@Param("entityTypeId") UUID paramUUID1, @Param("permissionId") UUID paramUUID2);
  
  @Select({"SELECT etp.id              AS etp_id,\n       etp.data            AS etp_data,\n       etp.description     AS etp_description,\n       etp.entity_types_id AS etp_entity_types_id,\n       etp.insert_instant  AS etp_insert_instant,\n       etp.is_default      AS etp_is_default,\n       etp.last_update_instant AS etp_last_update_instant,\n       etp.name            AS etp_name\n  FROM entity_type_permissions AS etp\n WHERE etp.entity_types_id = #{entityTypeId}\n   AND etp.name = #{name}\n"})
  @ResultMap({"EntityTypePermission"})
  EntityTypePermission retrievePermissionByName(@Param("entityTypeId") UUID paramUUID, @Param("name") String paramString);
  
  @Select({"SELECT\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entity_types AS et\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n WHERE et.id = #{id} ORDER BY et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name"})
  @ResultMap({"EntityType"})
  EntityType retrieveTypeById(@Param("id") UUID paramUUID);
  
  @Select({"SELECT\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entity_types AS et\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n WHERE et.name = #{name} ORDER BY et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name"})
  @ResultMap({"EntityType"})
  EntityType retrieveTypeByName(@Param("name") String paramString);
  
  @Select({"<script>SELECT\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entity_types AS et\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\nWHERE et.name = #{name}\n<if test=\"id != null\">AND et.id != #{id}</if>\nORDER BY et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name\n</script>"})
  @ResultMap({"EntityType"})
  EntityType retrieveTypeDuplicate(@Param("id") UUID paramUUID, @Param("name") String paramString);
  
  @Select({"<script>\nSELECT id FROM entity_types et\n<if test=\"name != null\">\n  WHERE LOWER(name) LIKE #{name}\n</if>\n<choose>\n  <when test=\"orderBy.equals('entityTypePermissionsCount asc')\">\n    ORDER BY (\n      SELECT COUNT(*)\n      FROM entity_type_permissions etp\n      WHERE et.id = etp.entity_types_id) ASC\n  </when>\n  <when test=\"orderBy.equals('entityTypePermissionsCount desc')\">\n    ORDER BY (\n      SELECT COUNT(*)\n      FROM entity_type_permissions etp\n      WHERE et.id = etp.entity_types_id) DESC\n  </when>\n  <otherwise>\n    <when test=\"orderBy != null\">\n      ORDER BY ${orderBy}\n    </when>\n  </otherwise>\n</choose>\nLIMIT #{numberOfResults}\nOFFSET #{startRow}\n</script>\n"})
  List<UUID> retrieveTypeIdsByCriteria(EntityTypeSearchCriteria paramEntityTypeSearchCriteria);
  
  @Select({"<script>SELECT\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id\n  FROM entity_types AS et\n    LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n    LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\nWHERE et.id IN (\n  <foreach collection=\"ids\" item=\"id\" separator=\",\">#{id}</foreach>\n)\nORDER BY et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name\n</script>\n"})
  @ResultMap({"EntityType"})
  List<EntityType> retrieveTypesByIds(@Param("ids") List<UUID> paramList);
  
  @Select({"<script>SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id,\n  eg.id                           AS eg_id,\n  eg.data                         AS eg_dataFromDatabase,\n  eg.insert_instant               AS eg_insertInstant,\n  eg.last_update_instant          AS eg_lastUpdateInstant,\n  eg.users_id                     AS eg_userId,\n  etp2.name                       AS eg_permissions\nFROM entity_user_grants AS eg\n  INNER JOIN entities AS e ON e.id = eg.entities_id\n  INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n  LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n  LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n  LEFT OUTER JOIN entity_user_grant_permissions AS eugp ON eg.id = eugp.entity_user_grants_id\n  LEFT OUTER JOIN entity_type_permissions AS etp2 ON eugp.entity_type_permissions_id = etp2.id\nWHERE eg.id IN (\n  <foreach collection=\"ids\" item=\"id\" separator=\",\">#{id}</foreach>\n)\nORDER BY eg.id, et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name, etp2.name\n</script>\n"})
  @ResultMap({"EntityGrant"})
  List<EntityGrant> retrieveUserGrantsByIds(@Param("ids") List<UUID> paramList);
  
  @Select({"SELECT\n  e.id                            AS e_id,\n  e.client_id                     AS e_client_id,\n  e.client_secret                 AS e_client_secret,\n  e.data                          AS e_data,\n  e.insert_instant                AS e_insert_instant,\n  e.last_update_instant           AS e_last_update_instant,\n  e.name                          AS e_name,\n  e.parent_id                     AS e_parent_id,\n  e.tenants_id                    AS e_tenants_id,\n  et.id                           AS et_id,\n  et.access_token_signing_keys_id AS et_access_token_signing_keys_id,\n  et.data                         AS et_data,\n  et.name                         AS et_name,\n  et.insert_instant               AS et_insert_instant,\n  et.last_update_instant          AS et_last_update_instant,\n  etp.id                          AS etp_id,\n  etp.data                        AS etp_data,\n  etp.description                 AS etp_description,\n  etp.entity_types_id             AS etp_entity_types_id,\n  etp.insert_instant              AS etp_insert_instant,\n  etp.is_default                  AS etp_is_default,\n  etp.last_update_instant         AS etp_last_update_instant,\n  etp.name                        AS etp_name,\n  CASE WHEN etvk.type = 'AccessTokenVerification' THEN etvk.keys_id END AS et_access_token_verification_keys_id,\n  eg.id                           AS eg_id,\n  eg.data                         AS eg_dataFromDatabase,\n  eg.insert_instant               AS eg_insertInstant,\n  eg.last_update_instant          AS eg_lastUpdateInstant,\n  eg.users_id                     AS eg_userId,\n  etp2.name                       AS eg_permissions\nFROM entity_user_grants AS eg\n  INNER JOIN entities AS e ON e.id = eg.entities_id\n  INNER JOIN entity_types AS et ON e.entity_types_id = et.id\n  LEFT OUTER JOIN entity_type_permissions AS etp ON et.id = etp.entity_types_id\n  LEFT OUTER JOIN entity_type_verification_keys AS etvk ON et.id = etvk.entity_types_id\n  LEFT OUTER JOIN entity_user_grant_permissions AS eugp ON eg.id = eugp.entity_user_grants_id\n  LEFT OUTER JOIN entity_type_permissions AS etp2 ON eugp.entity_type_permissions_id = etp2.id\n WHERE eg.entities_id = #{entityId} ORDER BY eg.id, et.id, etvk.type, etvk.is_default DESC, etvk.keys_id, etp.name, etp2.name"})
  @ResultMap({"EntityGrant"})
  List<EntityGrant> retrieveUserGrantsForEntity(@Param("entityId") UUID paramUUID);
  
  @Select({"<script>\nSELECT e.id\nFROM entities AS e INNER JOIN entity_types AS et ON e.entity_types_id = et.id\nWHERE (\n  LOWER(e.client_id) LIKE #{queryString} OR\n  LOWER(e.name) LIKE #{queryString} OR\n  LOWER(et.name) LIKE #{queryString}\n)\n<if test=\"tenantId != null\">\n  AND e.tenants_id = #{tenantId}\n</if>\nORDER BY ${orderBy}\nLIMIT #{numberOfResults}\nOFFSET #{startRow}\n</script>\n"})
  List<UUID> searchByTerm(@Param("tenantId") UUID paramUUID, @Param("queryString") String paramString1, @Param("numberOfResults") int paramInt1, @Param("startRow") int paramInt2, @Param("orderBy") String paramString2);
  
  @Select({"<script>\nSELECT COUNT(*)\nFROM entities AS e INNER JOIN entity_types AS et ON e.entity_types_id = et.id\nWHERE (\n  LOWER(e.client_id) LIKE #{queryString} OR\n  LOWER(e.name) LIKE #{queryString} OR\n  LOWER(et.name) LIKE #{queryString}\n)\n<if test=\"tenantId != null\">\n  AND e.tenants_id = #{tenantId}\n</if>\n</script>\n"})
  long searchByTermCount(@Param("tenantId") UUID paramUUID, @Param("queryString") String paramString);
  
  @Update({"UPDATE entities\n  SET client_secret       = #{clientSecret},\n      data                = #{dataToDatabase},\n      name                = #{name},\n      last_update_instant = #{lastUpdateInstant},\n      parent_id           = #{parentId}\n  WHERE id = #{id}\n"})
  void updateEntity(Entity paramEntity);
  
  @Update({"UPDATE entity_type_permissions\n  SET data                = #{dataToDatabase},\n      description         = #{description},\n      is_default          = #{isDefault},\n      last_update_instant = #{lastUpdateInstant}\n  WHERE id = #{id}\n"})
  void updatePermission(EntityTypePermission paramEntityTypePermission);
  
  @Update({"UPDATE entity_types\n  SET access_token_signing_keys_id = #{jwtConfiguration.accessTokenKeyId},\n      data                         = #{dataToDatabase},\n      name                         = #{name},\n      last_update_instant          = #{lastUpdateInstant}\n  WHERE id = #{id}\n"})
  void updateType(EntityType paramEntityType);
  
  @List({@Insert(value = {"INSERT INTO entity_entity_grants (id, data, insert_instant, last_update_instant, recipient_id, target_id)\nVALUES (#{grant.id}, #{grant.dataToDatabase}, #{grant.insertInstant}, #{grant.lastUpdateInstant}, #{grant.recipientEntityId}, #{entity.id})\nON DUPLICATE KEY UPDATE data = #{grant.dataToDatabase}, last_update_instant = #{grant.lastUpdateInstant}\n"}, databaseId = "mysql"), @Insert(value = {"INSERT INTO entity_entity_grants (id, data, insert_instant, last_update_instant, recipient_id, target_id)\nVALUES (#{grant.id}, #{grant.dataToDatabase}, #{grant.insertInstant}, #{grant.lastUpdateInstant}, #{grant.recipientEntityId}, #{entity.id})\nON CONFLICT (recipient_id, target_id) DO UPDATE SET data = EXCLUDED.data, last_update_instant = EXCLUDED.last_update_instant\n"}, databaseId = "postgresql")})
  void upsertEntityGrant(@Param("entity") Entity paramEntity, @Param("grant") EntityGrant paramEntityGrant);
  
  @List({@Insert(value = {"INSERT INTO entity_user_grants (id, data, entities_id, insert_instant, last_update_instant, users_id)\nVALUES (#{grant.id}, #{grant.dataToDatabase}, #{entity.id}, #{grant.insertInstant}, #{grant.lastUpdateInstant}, #{grant.userId})\nON DUPLICATE KEY UPDATE data = #{grant.dataToDatabase}, last_update_instant = #{grant.lastUpdateInstant}\n"}, databaseId = "mysql"), @Insert(value = {"INSERT INTO entity_user_grants (id, data, entities_id, insert_instant, last_update_instant, users_id)\nVALUES (#{grant.id}, #{grant.dataToDatabase}, #{entity.id}, #{grant.insertInstant}, #{grant.lastUpdateInstant}, #{grant.userId})\nON CONFLICT (entities_id, users_id) DO UPDATE SET data = EXCLUDED.data, last_update_instant = EXCLUDED.last_update_instant\n"}, databaseId = "postgresql")})
  void upsertUserGrant(@Param("entity") Entity paramEntity, @Param("grant") EntityGrant paramEntityGrant);
}
